from pathlib import Path

path = Path('/home/ubuntu/huqan-site/tr/blog/what-is-ai-agent-governance/index.html')
html = path.read_text()
common = {
    '<html lang="en">':'<html lang="tr">',
    'What Is AI Agent Governance? A Practical Guide | Huqan':'Yapay Zekâ Ajan Yönetişimi Nedir? Pratik Rehber | Huqan',
    'What Is AI Agent Governance? A Practical Guide':'Yapay Zekâ Ajan Yönetişimi Nedir? Pratik Rehber',
    'What Is AI Agent Governance?':'Yapay Zekâ Ajan Yönetişimi Nedir?',
    'How evidence, policy, approval, verification, and audit records keep AI agent work reviewable.':'Kanıt, politika, onay, doğrulama ve denetim kayıtlarının yapay zekâ ajanı işlerini nasıl incelemeye açık tuttuğunu öğrenin.',
    'AI agent governance is the set of evidence checks, policies, approvals, verification steps, and audit records that keep agent decisions reviewable.':'Yapay zekâ ajan yönetişimi; ajan kararlarını incelemeye açık tutan kanıt kontrolleri, politikalar, onaylar, doğrulama adımları ve denetim kayıtları bütünüdür.',
    'Huqan AI agent governance guide':'Huqan yapay zekâ ajan yönetişimi rehberi',
    'AI governance':'Yapay zekâ yönetişimi',
    'Understand / AI governance':'Anla / Yapay zekâ yönetişimi',
    'Primary navigation':'Ana navigasyon',
    '>Home<':'>Ana sayfa<',
    '>Journal<':'>Günlük<',
    '>Skip to content<':'>İçeriğe geç<',
    'Published 28 Aug 2026':'28 Ağu 2026 tarihinde yayınlandı',
    'Updated 28 Aug 2026':'28 Ağu 2026 güncellendi',
    'By Huqan Contributors':'Huqan Katkıcıları',
    '8 min read':'8 dk okuma',
    'Huqan / Journal':'Huqan / Günlük',
    'Huqan / Journal</a> / What Is AI Agent Governance?':'Huqan / Günlük</a> / Yapay Zekâ Ajan Yönetişimi Nedir?',
    'Short answer':'Kısa cevap',
    "AI agent governance</b> is the control layer between an agent's intent and the systems it can affect. It checks evidence and provenance, applies policy and risk rules, routes sensitive decisions for approval, and records what happened.":'Yapay zekâ ajan yönetişimi</b>, ajanın niyeti ile etkileyebileceği sistemler arasındaki kontrol katmanıdır. Kanıt ve provenance bilgisini kontrol eder, politika ve risk kurallarını uygular, hassas kararları onaya yönlendirir ve ne olduğunu kaydeder.',
    'AI systems already produce useful text, code, plans, and decisions. The harder question begins when an agent turns that output into a memory entry, a tool call, a file change, or an external action. The output may be plausible while its evidence, scope, or authority remains unclear.':'Yapay zekâ sistemleri yararlı metin, kod, plan ve kararlar üretebilir. Zor soru, bir ajanın bu çıktıyı hafıza kaydına, araç çağrısına, dosya değişikliğine veya dış eyleme dönüştürdüğü anda başlar. Çıktı makul görünebilir; ancak kanıtı, kapsamı veya yetkisi belirsiz kalabilir.',
    'Huqan is a local-first, partial-trust governance and verification layer for that boundary. Its repository describes a bounded set of primitives for claims, memory writes, and selected agent actions—not a universal truth engine or a promise that hallucinations disappear.':'Huqan bu sınır için yerel öncelikli, kısmi güvenli bir yönetişim ve doğrulama katmanıdır. Deposu; iddialar, hafıza yazımları ve seçili ajan eylemleri için sınırlı bir ilkel kümesini tanımlar. Huqan evrensel bir doğruluk motoru değildir ve halüsinasyonların ortadan kalkacağını vaat etmez.',
    'Why AI agents need a trust boundary':'Yapay zekâ ajanlarının neden güven sınırına ihtiyacı var',
    'A chatbot can stop at an answer. An agent can continue: it can write to memory, call a tool, update a record, or ask another system to act. Each transition increases the cost of an unsupported claim or an ambiguous instruction.':'Bir sohbet botu cevapta durabilir. Bir ajan devam edebilir: hafızaya yazabilir, araç çağırabilir, bir kaydı güncelleyebilir veya başka bir sistemden eylem isteyebilir. Her geçiş, desteklenmeyen bir iddianın veya belirsiz talimatın maliyetini artırır.',
    'Governance makes the transition explicit. Before a consequential action proceeds, the system should be able to answer: <b>what was requested, which evidence supported it, which workspace and policy applied, who approved it, and what record remains?</b>':'Yönetişim bu geçişi açık hale getirir. Sonuç doğuran bir eylem ilerlemeden önce sistem şu sorulara cevap verebilmelidir: <b>ne istendi, hangi kanıt destekledi, hangi çalışma alanı ve politika uygulandı, kim onayladı ve geriye hangi kayıt kaldı?</b>',
    'AI agent governance vs. AI guardrails':'Yapay zekâ ajan yönetişimi ve AI guardrail farkı',
    'These terms overlap, but they do not describe the same layer. A guardrail often filters an input or output, checks a topic, transforms PII, or pauses a tool call. Governance includes those controls when needed, but adds provenance, scope, verification, approval, decision context, and durable auditability.':'Bu terimler kesişir; ancak aynı katmanı anlatmaz. Bir guardrail genellikle girdi veya çıktıyı filtreler, konu kontrolü yapar, kişisel veriyi dönüştürür veya araç çağrısını duraklatır. Yönetişim gerektiğinde bu kontrolleri kapsar; ayrıca provenance, kapsam, doğrulama, onay, karar bağlamı ve kalıcı denetlenebilirlik ekler.',
    'Question':'Soru','Guardrails':'Guardrail\'ler','Governance':'Yönetişim','What does it inspect?':'Neyi inceler?','Inputs, outputs, tool calls, or runtime events.':'Girdileri, çıktıları, araç çağrılarını veya çalışma zamanı olaylarını.','Claims, evidence, provenance, memory writes, policies, approvals, and selected actions.':'İddiaları, kanıtı, provenance bilgisini, hafıza yazımlarını, politikaları, onayları ve seçili eylemleri.',
    'What is the result?':'Sonuç nedir?','Filter, transform, allow, or pause.':'Filtreleme, dönüştürme, izin verme veya duraklatma.','Allow, block, review, escalate, dry-run, plus the context and record behind that result.':'İzin verme, engelleme, inceleme, yükseltme veya dry-run; ayrıca sonucun arkasındaki bağlam ve kayıt.',
    'What happens later?':'Sonra ne olur?','Logs may show that a check ran.':'Loglar bir kontrolün çalıştığını gösterebilir.','A receipt or audit record can preserve why the decision was made and what changed.':'Bir receipt veya denetim kaydı kararın nedenini ve neyin değiştiğini koruyabilir.',
    'How AI agent governance works':'Yapay zekâ ajan yönetişimi nasıl çalışır',
    'A practical control flow is easier to understand when each stage has one job. The following sequence mirrors the bounded local flow documented by Huqan.':'Her aşamanın tek bir görevi olduğunda pratik kontrol akışını anlamak kolaylaşır. Aşağıdaki sıra Huqan tarafından belgelenen sınırlı yerel akışı izler.',
    '<b>Request:</b> the agent proposes a concrete action with a target and context.':'<b>İstek:</b> ajan, hedefi ve bağlamı olan somut bir eylem önerir.',
    '<b>Evidence:</b> the system collects the source, provenance, and workspace scope relevant to the request.':'<b>Kanıt:</b> sistem istekle ilgili kaynağı, provenance bilgisini ve çalışma alanı kapsamını toplar.',
    '<b>Verify:</b> deterministic checks look for support, contradiction, risk, and policy conflicts.':'<b>Doğrula:</b> deterministik kontroller destek, çelişki, risk ve politika çatışmalarını arar.',
    '<b>Approve:</b> sensitive mutations are routed to the appropriate human authority when required.':'<b>Onayla:</b> hassas değişiklikler gerektiğinde uygun insan yetkisine yönlendirilir.',
    '<b>Execute:</b> only an allowed action continues through the controlled boundary.':'<b>Uygula:</b> yalnızca izin verilen eylem kontrollü sınırdan ilerler.',
    '<b>Record:</b> the result, rationale, evidence, and decision become an auditable receipt.':'<b>Kaydet:</b> sonuç, gerekçe, kanıt ve karar denetlenebilir bir receipt kaydına dönüşür.',
    'Five pillars of a useful governance layer':'Kullanışlı bir yönetişim katmanının beş temeli','Pillar':'Temel','Direct answer':'Doğrudan cevap','What to verify':'Ne doğrulanmalı?',
    'Evidence':'Kanıt','What supports the claim or action?':'İddiayı veya eylemi ne destekliyor?','Source, freshness, relevance, and whether the evidence is actually attached.':'Kaynak, güncellik, uygunluk ve kanıtın gerçekten eklenmiş olup olmadığı.',
    'Provenance':'Provenance','Where did the information come from?':'Bilgi nereden geldi?','Origin, transformation, workspace, and links to the underlying record.':'Köken, dönüşüm, çalışma alanı ve temel kayda bağlantılar.',
    'Policy and risk':'Politika ve risk','What is allowed, blocked, or reviewable?':'Neye izin verilir, ne engellenir veya incelenir?','Deterministic rule, risk classification, and the configured action boundary.':'Deterministik kural, risk sınıflandırması ve yapılandırılmış eylem sınırı.',
    'Human approval':'İnsan onayı','Who can authorize a sensitive change?':'Hassas bir değişikliği kim yetkilendirebilir?','Separate approval state and actor; proposal should not equal approval.':'Ayrı onay durumu ve aktör; öneri onayla aynı şey olmamalıdır.',
    'Receipt and audit':'Receipt ve denetim','What can be reconstructed later?':'Daha sonra ne yeniden kurulabilir?','Request, decision, evidence, execution result, and durable receipt reference.':'İstek, karar, kanıt, uygulama sonucu ve kalıcı receipt referansı.',
    'Verification is not a promise of perfect truth':'Doğrulama kusursuz doğruluk sözü değildir','Verification is a scoped result. It can say that a claim is supported, contradicted, or unresolved within a configured evidence and runtime boundary. It cannot turn a local check into a universal certificate of truth.':'Doğrulama kapsamlı bir sonuçtur. Bir iddianın yapılandırılmış kanıt ve çalışma zamanı sınırı içinde desteklendiğini, çeliştiğini veya çözümsüz kaldığını söyleyebilir. Yerel bir kontrolü evrensel doğruluk sertifikasına dönüştüremez.',
    'Confidence is not truth. Verify before you trust. — HUQAN repository positioning':'Güven, doğruluk değildir. Güvenmeden önce doğrulayın. — HUQAN depo konumlandırması',
    'This distinction matters for AI search content too. A strong page should state what it can verify, what sources it used, and where the boundary ends. That language is more useful to readers and less likely to turn a bounded test into an unsupported marketing claim.':'Bu ayrım yapay zekâ arama içeriği için de önemlidir. Güçlü bir sayfa neyi doğrulayabildiğini, hangi kaynakları kullandığını ve sınırın nerede bittiğini söylemelidir. Bu dil okuyucu için daha yararlıdır ve sınırlı bir testi desteklenmeyen pazarlama iddiasına dönüştürme riskini azaltır.',
    'What is a Trust Receipt?':'Trust Receipt nedir?','A <b>Trust Receipt</b> is a bounded, auditable record of a supported verification or action-governance flow. It can preserve evidence, provenance, scope, risk, review, approval, and the resulting decision. It is not a universal certificate that a claim is true.':'<b>Trust Receipt</b>, desteklenen bir doğrulama veya eylem yönetişimi akışının sınırlı ve denetlenebilir kaydıdır. Kanıtı, provenance bilgisini, kapsamı, riski, incelemeyi, onayı ve sonuç kararını koruyabilir. Bir iddianın doğru olduğuna dair evrensel sertifika değildir.',
    'In practice, the receipt is the handoff between a live decision and later review. It lets a developer, operator, or auditor ask what happened without relying on the model\'s transient context.':'Pratikte receipt, canlı karar ile sonraki inceleme arasındaki aktarım kaydıdır. Geliştirici, operatör veya denetçi modelin geçici bağlamına güvenmeden ne olduğunu sorabilir.',
    'Why local-first matters':'Yerel öncelikli yaklaşım neden önemlidir','Huqan\'s core local graph, verification, gate, and receipt paths are designed to run without a hosted model or cloud service. The repository exposes CLI, REST, MCP, library, local UI, and read-only viewer surfaces on supported paths.':'Huqan\'ın temel yerel grafik, doğrulama, kapı ve receipt yolları barındırılan model veya bulut servisi olmadan çalışacak şekilde tasarlanmıştır. Depo, desteklenen yollarda CLI, REST, MCP, kütüphane, yerel arayüz ve salt-okunur görüntüleyici yüzeyleri sunar.',
    'Local-first does not mean every optional adapter or deployment mode is cloud-independent. It means the core trust boundary can be owned and inspected close to the workflow that needs it.':'Yerel öncelikli yaklaşım, her isteğe bağlı adaptörün veya dağıtım modunun buluttan bağımsız olduğu anlamına gelmez. Temel güven sınırının ona ihtiyaç duyan iş akışına yakın biçimde sahiplenilebilmesi ve incelenebilmesi anlamına gelir.',
    'How to start implementing governance':'Yönetişimi uygulamaya nasıl başlanır','Start with one consequential path instead of trying to govern every connector at once. Pick a memory write, file mutation, data export, or MCP action that already has a clear owner and risk profile.':'Her bağlayıcıyı aynı anda yönetmeye çalışmak yerine tek bir sonuç doğuran yolla başlayın. Sahibi ve risk profili belli bir hafıza yazımı, dosya değişikliği, veri dışa aktarımı veya MCP eylemi seçin.',
    'Define the request envelope: agent, action, target, workspace, and context.':'İstek zarfını tanımlayın: ajan, eylem, hedef, çalışma alanı ve bağlam.',
    'List the evidence and provenance fields that must be present.':'Mevcut olması gereken kanıt ve provenance alanlarını listeleyin.',
    'Write the deterministic outcomes: allow, block, review, escalate, or dry-run.':'Deterministik sonuçları yazın: izin ver, engelle, incele, yükselt veya dry-run.',
    'Separate proposal from approval and execution.':'Öneriyi onaydan ve uygulamadan ayırın.',
    'Emit a receipt that a different person can read without the original model session.':'Başka bir kişinin ilk model oturumu olmadan okuyabileceği bir receipt üretin.',
    'For a concrete local starting point, run the ':'Somut bir yerel başlangıç için ',
    'quickstart</a> and inspect the generated receipt. To compare the boundary with a programmable guardrail layer, read ':'quickstart</a> komutunu çalıştırın ve üretilen receipt kaydını inceleyin. Sınırı programlanabilir bir guardrail katmanıyla karşılaştırmak için ',
    'Huqan vs. NeMo Guardrails':'Huqan ve NeMo Guardrails',
    'the best AI governance tools for AI agents':'yapay zekâ ajanları için en iyi yönetişim araçları',
    'Frequently asked questions':'Sık sorulan sorular',
    'What is AI agent governance?':'Yapay zekâ ajan yönetişimi nedir?',
    'Why do AI agents need governance?':'Yapay zekâ ajanlarının yönetişime neden ihtiyacı var?',
    'What is the difference between AI guardrails and AI governance?':'AI guardrail ve yapay zekâ yönetişimi arasındaki fark nedir?',
    'Can AI governance eliminate hallucinations?':'Yapay zekâ yönetişimi halüsinasyonları ortadan kaldırabilir mi?',
    'What should an AI governance system record?':'Bir yapay zekâ yönetişim sistemi ne kaydetmeli?',
    "AI agent governance is the set of evidence checks, policies, approvals, verification steps, and audit records that keep an agent's decisions reviewable before they change trusted state or affect an external system.":'Yapay zekâ ajan yönetişimi; bir ajanın kararlarını güvenilir durumu değiştirmeden veya dış sistemi etkilemeden önce incelemeye açık tutan kanıt kontrolleri, politikalar, onaylar, doğrulama adımları ve denetim kayıtları bütünüdür.',
    'Agents can turn model output into memory writes, tool calls, or external actions. Governance adds an explicit boundary for evidence, risk, approval, and recording so people can challenge a decision instead of treating model output as authority.':'Ajanlar model çıktısını hafıza yazımlarına, araç çağrılarına veya dış eylemlere dönüştürebilir. Yönetişim; kanıt, risk, onay ve kayıt için açık bir sınır ekler, böylece insanlar model çıktısını otorite saymak yerine kararı sorgulayabilir.',
    'Guardrails usually filter or constrain inputs, outputs, or tool calls at runtime. Governance is broader: it also preserves provenance, scope, approval state, verification results, and an auditable record of the decision.':'Guardrail\'ler genellikle girdileri, çıktıları veya araç çağrılarını çalışma zamanında filtreler ya da sınırlar. Yönetişim daha geniştir: provenance, kapsam, onay durumu, doğrulama sonuçları ve kararın denetlenebilir kaydını da korur.',
    'No. Governance cannot guarantee that every model output is true. It can make evidence, uncertainty, contradiction, policy, and review explicit on the paths it covers.':'Hayır. Yönetişim her model çıktısının doğru olduğunu garanti edemez. Kapsadığı yollarda kanıtı, belirsizliği, çelişkiyi, politikayı ve incelemeyi açık hale getirebilir.',
    'A useful record can include the agent, request, target, evidence, provenance, workspace scope, risk, policy result, approval, execution result, and a durable receipt or audit reference.':'Kullanışlı bir kayıt; ajanı, isteği, hedefi, kanıtı, provenance bilgisini, çalışma alanı kapsamını, riski, politika sonucunu, onayı, uygulama sonucunu ve kalıcı bir receipt veya denetim referansını içerebilir.',
    'Sources and scope:':'Kaynaklar ve kapsam:',
    'This guide reflects Huqan repository materials checked on 28 Aug 2026. Product capabilities remain bounded by the specific adapter, policy, workspace, approval, and runtime path that supports them.':'Bu rehber 28 Ağu 2026 tarihinde kontrol edilen Huqan depo materyallerini yansıtır. Ürün yetenekleri, onları destekleyen belirli adaptör, politika, çalışma alanı, onay ve çalışma zamanı yoluyla sınırlıdır.',
    'Huqan canonical repository README':'Huqan kanonik depo README\'si',
    'especially “What is HUQAN?”, “How it works”, “Current capabilities”, and “Current scope”.':'özellikle “HUQAN nedir?”, “Nasıl çalışır?”, “Mevcut yetenekler” ve “Mevcut kapsam” bölümleri.',
    'Google Search Central: Google\'s Guide to Optimizing for Generative AI Features on Google Search':'Google Search Central: Google Arama\'da üretken yapay zekâ özellikleri için optimizasyon rehberi',
    'Last reviewed 28 Aug 2026. Pricing and third-party product details are not covered in this guide.':'Son inceleme: 28 Ağu 2026. Bu rehberde fiyatlandırma ve üçüncü taraf ürün ayrıntıları ele alınmamıştır.',
    'Journal':'Günlük',
    'Canonical repository':'Kanonik depo',
    'Contact':'İletişim',
}
for old, new in common.items():
    html = html.replace(old, new)
html = html.replace('href="https://huqan.com/blog/what-is-ai-agent-governance/"','href="https://huqan.com/tr/blog/what-is-ai-agent-governance/"')
html = html.replace('content="https://huqan.com/blog/what-is-ai-agent-governance/"','content="https://huqan.com/tr/blog/what-is-ai-agent-governance/"')
html = html.replace('content="https://huqan.com/blog/what-is-ai-agent-governance/#','content="https://huqan.com/tr/blog/what-is-ai-agent-governance/#')
html = html.replace('href="/blog/"','href="/tr/blog/"')
html = html.replace('href="/blog/huqan-vs-nemo-guardrails/"','href="/tr/blog/huqan-vs-nemo-guardrails/"')
html = html.replace('href="/blog/best-ai-governance-tools/"','href="/tr/blog/best-ai-governance-tools/"')
html = html.replace('href="/blog/what-is-ai-agent-governance/"','href="/tr/blog/what-is-ai-agent-governance/"')
path.write_text(html)
print('Localized', path)
