from pathlib import Path

path = Path('/home/ubuntu/huqan-site/tr/blog/index.html')
html = path.read_text()
replacements = {
    '<html lang="en">': '<html lang="tr">',
    'Huqan Journal: practical guides to AI agent governance, verification, provenance, memory safety, action approval, and Trust Receipts.': 'Huqan Günlüğü: yapay zekâ ajan yönetişimi, doğrulama, provenance, hafıza güvenliği, eylem onayı ve Trust Receipt üzerine pratik rehberler.',
    'Huqan Journal | AI Governance, Verification &amp; Trust': 'Huqan Günlüğü | Yapay Zekâ Yönetişimi, Doğrulama ve Güven',
    'Practical, source-backed notes on governing AI claims, memory writes, and selected agent actions.': 'Yapay zekâ iddiaları, hafıza yazımları ve seçili ajan eylemlerini yönetmek için kaynaklı pratik notlar.',
    'Huqan Journal about AI governance and verification': 'Yapay zekâ yönetişimi ve doğrulama hakkında Huqan Günlüğü',
    'Practical, source-backed notes on AI agent governance, verification, provenance, memory safety, action approval, and Trust Receipts.': 'Yapay zekâ ajan yönetişimi, doğrulama, provenance, hafıza güvenliği, eylem onayı ve Trust Receipt üzerine kaynaklı pratik notlar.',
    'Huqan / Journal': 'Huqan / Günlük',
    'Primary navigation': 'Ana navigasyon',
    '>Home<': '>Ana sayfa<',
    '>How it works<': '>Nasıl çalışır<',
    '>Journal<': '>Günlük<',
    'lang="en" hreflang="en"': 'lang="en" hreflang="en"',
    'lang="tr" hreflang="tr"': 'lang="tr" hreflang="tr"',
    '>Clear answers for<br><em>high-stakes AI.</em><': '>Yüksek riskli yapay zekâ<br><em>için açık cevaplar.</em><',
    'Practical, source-backed notes on AI agent governance, evidence, verification, memory admission, action approval, and Trust Receipts. The goal is simple: help teams understand what an AI system did before they trust what it changed.': 'Yapay zekâ ajan yönetişimi, kanıt, doğrulama, hafıza kabulü, eylem onayı ve Trust Receipt üzerine kaynaklı pratik notlar. Amaç basit: ekiplerin bir yapay zekâ sisteminin neyi değiştirdiğine güvenmeden önce ne yaptığını anlamasına yardımcı olmak.',
    'aria-label="Journal categories"': 'aria-label="Günlük kategorileri"',
    '>All notes<': '>Tüm notlar<',
    '>Understand<': '>Anla<',
    '>Compare<': '>Karşılaştır<',
    '>Build<': '>İnşa et<',
    '>Understand the boundary.<': '>Sınırı anlayın.<',
    'Start with the concepts behind evidence-bound AI work. Each guide leads with a direct answer and links to the repository sources that support it.': 'Kanıta bağlı yapay zekâ işinin arkasındaki kavramlarla başlayın. Her rehber doğrudan bir cevap verir ve onu destekleyen depo kaynaklarına bağlanır.',
    'Understand / Guide': 'Anla / Rehber',
    'What Is AI Agent Governance?': 'Yapay zekâ ajan yönetişimi nedir?',
    "AI agent governance is the set of policies, evidence checks, approvals, and audit records that keep an agent's decisions reviewable before they change trusted state.": 'Yapay zekâ ajan yönetişimi; bir ajanın kararlarını güvenilir durumu değiştirmeden önce incelemeye açık tutan politika, kanıt kontrolü, onay ve denetim kayıtları bütünüdür.',
    '8 min read': '8 dk okuma',
    '28 Aug 2026': '28 Ağu 2026',
    'Read the guide': 'Rehberi oku',
    'Understand / Verification': 'Anla / Doğrulama',
    'AI Hallucination Prevention Starts With Verification': 'Yapay zekâ halüsinasyonlarını önleme doğrulamayla başlar',
    'Why retrieval, provenance, contradiction checks, and explicit uncertainty work together—and why no single layer can promise perfect truth.': 'Getirme, provenance, çelişki kontrolleri ve açık belirsizliğin birlikte nasıl çalıştığı; hiçbir katmanın kusursuz doğruluk sözü veremeyeceği.',
    'Coming soon': 'Yakında',
    'Source-backed': 'Kaynaklı',
    'Preview the idea': 'Fikre göz at',
    'Understand / Trust Receipt': 'Anla / Trust Receipt',
    'What Is a Trust Receipt?': 'Trust Receipt nedir?',
    'A plain-language explanation of the evidence, scope, policy, approval, decision, and audit context a bounded receipt can preserve.': 'Sınırlı bir receipt kaydının koruyabileceği kanıt, kapsam, politika, onay, karar ve denetim bağlamının sade açıklaması.',
    'Canonical concept': 'Kanonik kavram',
    '>Compare the right layer.<': '>Doğru katmanı karşılaştırın.<',
    'Different tools own different boundaries. These comparisons focus on the decision a team is actually trying to make.': 'Farklı araçlar farklı sınırların sorumluluğunu taşır. Bu karşılaştırmalar ekiplerin gerçekten vermeye çalıştığı karara odaklanır.',
    'Compare / Head-to-head': 'Karşılaştır / Başa baş',
    'Huqan vs. NeMo Guardrails': 'Huqan ve NeMo Guardrails',
    'Huqan centers evidence, provenance, scope, policy, approval, and receipts. NeMo Guardrails centers programmable guardrails around LLM interactions.': 'Huqan kanıt, provenance, kapsam, politika, onay ve receipt kayıtlarına odaklanır. NeMo Guardrails ise LLM etkileşimleri etrafında programlanabilir guardrail katmanına odaklanır.',
    '9 min read': '9 dk okuma',
    'Compare boundaries': 'Sınırları karşılaştır',
    'Compare / Practical': 'Karşılaştır / Pratik',
    'Guardrails vs. Governance': 'Guardrails ve yönetişim',
    'A decision guide for distinguishing output filtering, runtime controls, evaluation, governance, and auditability.': 'Çıktı filtreleme, çalışma zamanı kontrolleri, değerlendirme, yönetişim ve denetlenebilirlik arasındaki farkları anlatan karar rehberi.',
    'Decision guide': 'Karar rehberi',
    'Compare / MCP': 'Karşılaştır / MCP',
    'MCP Gateway vs. Action Governance': 'MCP Gateway ve eylem yönetişimi',
    'Container isolation and server lifecycle matter, but they do not by themselves create an evidence-bound decision record for an agent action.': 'Konteyner izolasyonu ve sunucu yaşam döngüsü önemlidir; ancak tek başına bir ajan eylemi için kanıta bağlı karar kaydı oluşturmaz.',
    'Developer guide': 'Geliştirici rehberi',
    '>Build with evidence.<': '>Kanıtla inşa edin.<',
    'Implementation notes keep the practical boundary visible: what is tested, what is configured, and what still needs dedicated proof.': 'Uygulama notları pratik sınırı görünür tutar: ne test edildi, ne yapılandırıldı ve neyin hâlâ özel kanıta ihtiyacı var.',
    'Explore / Listicle': 'Keşfet / Liste',
    '5 Best AI Governance Tools for AI Agents': '2026 için en iyi 5 yapay zekâ yönetişimi aracı',
    'A focused shortlist of tools for governance, guardrails, MCP operations, evaluation, and evidence-bound decisions—without pretending they solve the same problem.': 'Yönetişim, guardrail, MCP operasyonları, değerlendirme ve kanıta bağlı kararlar için; aynı problemi çözdüklerini iddia etmeyen odaklı kısa liste.',
    'See the shortlist': 'Kısa listeyi gör',
    'Build / Local-first': 'İnşa et / Yerel öncelikli',
    'Run AI Verification Locally': 'Yapay zekâ doğrulamayı yerelde çalıştırın',
    'A technical starting point for a local CLI, graph-backed verification, policy gates, and receipts without requiring a hosted model.': 'Barındırılan model gerektirmeden yerel CLI, grafik destekli doğrulama, politika kapıları ve receipt kayıtları için teknik başlangıç.',
    'Quickstart': 'Hızlı başlangıç',
    'Build / Audit': 'İnşa et / Denetim',
    'Design an Auditable Agent Action': 'Denetlenebilir bir ajan eylemi tasarlayın',
    'Map an action request to evidence, risk, approval, execution, and a durable record that can be challenged later.': 'Bir eylem isteğini kanıt, risk, onay, uygulama ve daha sonra sorgulanabilecek kalıcı bir kayda bağlayın.',
    'Architecture': 'Mimari',
    'Models generate. Agents act. Huqan judges.': 'Modeller üretir. Ajanlar harekete geçer. Huqan hükmeder.',
    'Explore the product boundary in the live demo, inspect the canonical repository, or discuss a bounded pilot for a workflow that needs evidence before action.': 'Canlı demoda ürün sınırını inceleyin, kanonik depoya bakın veya eylemden önce kanıta ihtiyaç duyan bir iş akışı için sınırlı bir pilot görüşün.',
    'Explore Huqan': "Huqan'ı keşfet",
    'Canonical repository': 'Kanonik depo',
    'Contact': 'İletişim',
}
for old, new in replacements.items():
    html = html.replace(old, new)
path.write_text(html)
print('Localized', path)
